import type { Config } from "tailwindcss"
const defaultTheme = require("tailwindcss/defaultTheme")

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "brand-red": "#f5333f",
        "brand-red-light": "#f5636f",
        swamp: "#00141f",
        "mine-shaft": "#222222",
        mystic: "#e7eef1",
        white: "#ffffff",
        pomegranate: "#f5333f",
        saffron: "#f2c738",
        tiber: "#0a2b3d",
        nobel: "#b7b7b7",
        "big-stone": "#17313b",
        "red-orange": "#ff3d2e",
        gondola: "#150c0c",
        "aqua-spring": "#f1f8fb",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        inter: ["var(--font-inter)"],
        "work-sans": ["var(--font-work-sans)"],
        ...defaultTheme.fontFamily,
      },
      fontSize: {
        "10": "10px",
        "11": "11px",
        "14": "14px",
        "16": "16px",
        "22": "22px",
        "24": "24px",
        "36": "36px",
        "64": "64px",
        "92": "92px",
        "120": "120px",
      },
      lineHeight: {
        "12": "12px",
        "15.4": "15.4px",
        "16.8": "16.8px",
        "17.6": "17.6px",
        "18.4": "18.4px",
        "18.7": "18.7px",
        "19.9": "19.9px",
        "24.2": "24.2px",
        "28": "28px",
        "28.6": "28.6px",
        "30.4": "30.4px",
        "33": "33px",
        "36": "36px",
        "46.8": "46.8px",
        "70.4": "70.4px",
        "101.2": "101.2px",
        "132": "132px",
      },
      backgroundImage: {
        "gradient-brand": "linear-gradient(180deg, #e5273e 50%, #f5333f 50%)",
        "gradient-dark": "linear-gradient(180deg, #00141f 50%, #0a2b3d 50%)",
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
        "26": "6.5rem",
        "30": "7.5rem",
        "34": "8.5rem",
        "38": "9.5rem",
        "42": "10.5rem",
        "46": "11.5rem",
        "50": "12.5rem",
        "54": "13.5rem",
        "58": "14.5rem",
        "62": "15.5rem",
        "66": "16.5rem",
        "70": "17.5rem",
        "74": "18.5rem",
        "78": "19.5rem",
        "82": "20.5rem",
        "86": "21.5rem",
        "90": "22.5rem",
        "94": "23.5rem",
        "98": "24.5rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
